name: Pipe NodeJs

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]
      
  schedule:
    - cron: '0 12 1-15 * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm run test
